### ISSUE TITLE
EPIC: Docpoc

### ISSUE THREAD

**Issue by joostvanderborg** [GemeenteNijmegen/docpoc#1]
```[tasklist]
### Tasks
- [x] Vertaling geefLijstZaakDocumenten->objectInformatieObjecten
- [x] Vertaling geefZaakDocumentLezen -> enkelVoudigInformatieObject
- [x] Infra-inrichting
- [ ] Downloads mogelijk maken
```
